### ISSUE TITLE
Bug Report: Erro no Checkout

### ISSUE THREAD

**Issue by NaulEpilef** [pagarme/woocommerce#469]
## Descrição
Alguns clientes estão enfrentando problemas ao realizar o checkout de compras. O erro não ocorre com todos os clientes, mas acontece de forma intermitente. A maioria dos clientes consegue completar a compra sem problemas.

Abaixo estão detalhes do erro e capturas de tela relacionadas.

## Detalhe do Erro

- Mensagem de Erro:

```shell
Exception: Order #0 : Call to undefined method Pagarme\Core\Kernel\ValueObjects\CardBrand::() in /home/u917043205/domains/dominio.com.br/public_html/wp-content/plugins/pagarme-payments-for-woocommerce/vendor/pagarme/ecommerce-module-core/src/Kernel/Services/OrderService.php:334
Stack trace:
#0 /home/u917043205/domains/dominio.com.br/public_html/wp-content/plugins/pagarme-payments-for-woocommerce/src/Controller/Orders.php(64): Pagarme\Core\Kernel\Services\OrderService->createOrderAtPagarme()
#1 /home/u917043205/domains/dominio.com.br/public_html/wp-content/plugins/pagarme-payments-for-woocommerce/src/Model/Checkout.php(129): Woocommerce\Pagarme\Controller\Orders->create_order()
#2 /home/u917043205/domains/dominio.com.br/public_html/wp-content/plugins/pagarme-payments-for-woocommerce/src/Controller/Gateways/AbstractGateway.php(199): Woocommerce\Pagarme\Model\Checkout->process()
#3 /home/u917043205/domains/dominio.com.br/public_html/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1062): Woocommerce\Pagarme\Controller\Gateways\AbstractGateway->process_payment()
#4 /home/u917043205/domains/dominio.com.br/public_html/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1293): WC_Checkout->process_order_payment()
#5 /home/u917043205/domains/dominio.com.br/public_html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(520): WC_Checkout->process_checkout()
#6 /home/u917043205/domains/dominio.com.br/public_html/wp-includes/class-wp-hook.php(324): WC_AJAX::checkout()
#7 /home/u917043205/domains/dominio.com.br/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#8 /home/u917043205/domains/dominio.com.br/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#9 /home/u917043205/domains/dominio.com.br/public_html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(96): do_action()
#10 /home/u917043205/domains/dominio.com.br/public_html/wp-includes/class-wp-hook.php(324): WC_AJAX::do_wc_ajax()
#11 /home/u917043205/domains/dominio.com.br/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#12 /home/u917043205/domains/dominio.com.br/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#13 /home/u917043205/domains/dominio.com.br/public_html/wp-includes/template-loader.php(13): do_action()
#14 /home/u917043205/domains/dominio.com.br/public_html/wp-blog-header.php(19): require_once('/home/u91704320...')
#15 /home/u917043205/domains/dominio.com.br/public_html/index.php(17): require('/home/u91704320...')
#16 {main}
```

- Log do WooCommerce
```shell
Order.INFO: Order #0 : State Change
Version: m: 3.3.1 c: 2.4.1 p:  Wordpress/6.5.5 Woocommerce/9.0.2 
From: /home/u917043205/domains/dominio.com.br/public_html/wp-content/plugins/pagarme-payments-for-woocommerce/vendor/pagarme/ecommerce-module-core/src/Kernel/Services/OrderService.php:248 -> Pagarme\Core\Kernel\Abstractions\AbstractPlatformOrderDecorator::setState
{
    "from": "new",
    "to": "new"
}
Order.INFO: Order #0 : Status Change
Version: m: 3.3.1 c: 2.4.1 p:  Wordpress/6.5.5 Woocommerce/9.0.2 
From: /home/u917043205/domains/dominio.com.br/public_html/wp-content/plugins/pagarme-payments-for-woocommerce/vendor/pagarme/ecommerce-module-core/src/Kernel/Services/OrderService.php:249 -> Pagarme\Core\Kernel\Abstractions\AbstractPlatformOrderDecorator::setStatus
{
    "from": "pending",
    "to": "pending"
}
Order.INFO: Order #0 : Call to undefined method Pagarme\Core\Kernel\ValueObjects\CardBrand::()
Version: m: 3.3.1 c: 2.4.1 p:  Wordpress/6.5.5 Woocommerce/9.0.2 
From: /home/u917043205/domains/dominio.com.br/public_html/wp-content/plugins/pagarme-payments-for-woocommerce/src/Controller/Orders.php:64 -> Pagarme\Core\Kernel\Services\OrderService::createOrderAtPagarme
[]
Order.INFO: Order #0 : Failed to create order at Pagarme!
Version: m: 3.3.1 c: 2.4.1 p:  Wordpress/6.5.5 Woocommerce/9.0.2 
From: /home/u917043205/domains/dominio.com.br/public_html/wp-content/plugins/pagarme-payments-for-woocommerce/vendor/pagarme/ecommerce-module-core/src/Kernel/Services/OrderService.php:332 -> Pagarme\Core\Payment\Services\ResponseHandlers\ErrorExceptionHandler::handle
[]
Order.ERROR: Order #0 : Call to undefined method Pagarme\Core\Kernel\ValueObjects\CardBrand::() | Exception code: 400
Version: m: 3.3.1 c: 2.4.1 p:  Wordpress/6.5.5 Woocommerce/9.0.2 
From: /home/u917043205/domains/dominio.com.br/public_html/wp-content/plugins/pagarme-payments-for-woocommerce/vendor/pagarme/ecommerce-module-core/src/Kernel/Services/OrderService.php:332 -> Pagarme\Core\Payment\Services\ResponseHandlers\ErrorExceptionHandler::handle
[]
```

- Captura de Tela da Nota:

![image](https://github.com/pagarme/woocommerce/assets/49931595/a35abef5-9a0e-47bf-839b-38abdbf53079)

- Captura de Tela do Erro no Celular do Cliente:

![image](https://github.com/pagarme/woocommerce/assets/49931595/1b47adf0-2b45-4b16-a2a0-9000cc5d90bc)

## Passos para Reproduzir
Atualmente, não sei como reproduzir o erro de forma consistente. Ele parece ocorrer de maneira aleatória para alguns clientes durante o processo de checkout.

Agradeço qualquer ajuda para identificar e corrigir esse problema.

**Comment by RafaMelazzo** [comment]
Bom dia @NaulEpilef! Tudo bem?

Sobre a exception `Call to undefined method Pagarme\Core\Kernel\ValueObjects\CardBrand::()`, esse erro pode ocorrer quando não há bandeira autorizada nas configurações de cartão de crédito. Acesse as configurações de cartão de crédito do plugin e salve para registrar essa opção no banco de dados, e acompanhe para verificar que esse erro não aconteça novamente, por favor.

Sobre o checkout não exibir formas de pagamento para o comprador, isso não é relacionado com o nosso plugin. É uma responsabilidade do próprio WooCommerce. Isso pode ocorrer por diversos problemas, como problemas na certificação ssl do seu site ou o país selecionado pelo comprador no checkout, por exemplo.

**Comment by NaulEpilef** [comment]
Bom dia, obrigado pelo retorno @RafaMelazzo 

Eu acessei as configurações do cartão de crédito e confirmei que todas as bandeiras estão selecionadas. Seguindo o seu conselho, re-salvei as configurações sem fazer nenhuma alteração. Vou monitorar a situação nos próximos dias para garantir que tudo está funcionando corretamente. Agradeço pela ajuda!

**Comment by NaulEpilef** [comment]
Olá @RafaMelazzo, eu estava esperançoso que funcionaria, mas hoje o erro se repetiu, teria outra coisa que você recomenda eu tentar?

**Comment by RafaMelazzo** [comment]
Bom dia @NaulEpilef!

Vamos efetuar alguns testes no seu site para verificar o que pode estar ocorrendo.

Pode nos enviar no e-mail opensource@pagar.me a lista dos plugins instalados na sua loja, por favor?

**Comment by leandrosantoss** [comment]
Tive esse problema com um cliente IOS usando Chrome, ao mudar para o Edge funcionou.

Não cheguei a validar se era o Chrome desatualizado.
