### ISSUE TITLE
Erro Fatal com Woocommerce 9.4.2

### ISSUE THREAD

**Issue by thiagommeneses** [pagarme/woocommerce#519]
# Bug

### Descrição
Na página de Lista de Produtos ocorre erro fatal. Este problema ocorre após a atualização para o Woocommerce 9.4.2, na versão anterior está tudo OK.

### Como reproduzir
Atualize o Woocommerce para a versão 9.4.2 e acesse a página de produtos cadastrados.

### Evidências
Fatal error: Uncaught Error: Call to undefined function wc_get_chosen_shipping_method_ids() in /home/u459490417/domains/closetcollection.com.br/public_html/novo/wp-content/plugins/woocommerce/includes/class-wc-customer.php:189 Stack trace: #0 /home/u459490417/domains/closetcollection.com.br/public_html/novo/wp-content/plugins/woocommerce/includes/class-wc-tax.php(462): WC_Customer->get_taxable_address() #1 /home/u459490417/domains/closetcollection.com.br/public_html/novo/wp-content/plugins/woocommerce/includes/class-wc-tax.php(484): WC_Tax::get_tax_location() #2 /home/u459490417/domains/closetcollection.com.br/public_html/novo/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php(408): WC_Tax::get_rates() #3 /home/u459490417/domains/closetcollection.com.br/public_html/novo/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php(261): WC_Product_Variable_Data_Store_CPT->get_price_hash() #4 /home/u459490417/domains/closetcollection.com.br/public_html/novo/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(224): WC_Product_Variable_Data_Store_CPT->read_price_data() #5 /home/u459490417/domains/closetcollection.com.br/public_html/novo/wp-content/plugins/woocommerce/includes/class-wc-product-variable.php(97): WC_Data_Store->__call() #6 /home/u459490417/domains/closetcollection.com.br/public_html/novo/wp-content/plugins/woocommerce/includes/class-wc-product-variable.php(165): WC_Product_Variable->get_variation_prices() #7 /home/u459490417/domains/closetcollection.com.br/public_html/novo/wp-content/plugins/woocommerce/includes/admin/list-tables/class-wc-admin-list-table-products.php(217): WC_Product_Variable->get_price_html() #8 /home/u459490417/domains/closetcollection.com.br/public_html/novo/wp-content/plugins/woocommerce/includes/admin/list-tables/abstract-class-wc-admin-list-table.php(261): WC_Admin_List_Table_Products->render_price_column() #9 /home/u459490417/domains/closetcollection.com.br/public_html/novo/wp-includes/class-wp-hook.php(324): WC_Admin_List_Table->render_columns() #10 /home/u459490417/domains/closetcollection.com.br/public_html/novo/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #11 /home/u459490417/domains/closetcollection.com.br/public_html/novo/wp-includes/plugin.php(517): WP_Hook->do_action() #12 /home/u459490417/domains/closetcollection.com.br/public_html/novo/wp-admin/includes/class-wp-posts-list-table.php(1403): do_action() #13 /home/u459490417/domains/closetcollection.com.br/public_html/novo/wp-admin/includes/class-wp-list-table.php(1802): WP_Posts_List_Table->column_default() #14 /home/u459490417/domains/closetcollection.com.br/public_html/novo/wp-admin/includes/class-wp-posts-list-table.php(1437): WP_List_Table->single_row_columns() #15 /home/u459490417/domains/closetcollection.com.br/public_html/novo/wp-admin/includes/class-wp-posts-list-table.php(839): WP_Posts_List_Table->single_row() #16 /home/u459490417/domains/closetcollection.com.br/public_html/novo/wp-admin/includes/class-wp-posts-list-table.php(815): WP_Posts_List_Table->_display_rows() #17 /home/u459490417/domains/closetcollection.com.br/public_html/novo/wp-admin/includes/class-wp-list-table.php(1712): WP_Posts_List_Table->display_rows() #18 /home/u459490417/domains/closetcollection.com.br/public_html/novo/wp-admin/includes/class-wp-list-table.php(1639): WP_List_Table->display_rows_or_placeholder() #19 /home/u459490417/domains/closetcollection.com.br/public_html/novo/wp-admin/edit.php(503): WP_List_Table->display() #20 {main} thrown in /home/u459490417/domains/closetcollection.com.br/public_html/novo/wp-content/plugins/woocommerce/includes/class-wc-customer.php on line 189
Ocorreu um erro crítico neste site. Verifique a caixa de entrada do e-mail do administrador do site para obter instruções. Se continuar a ter problemas, tente o [fórum de suporte](https://br.wordpress.org/support/forums/) .

[Saiba mais sobre a como resolver problemas do WordPress.](https://wordpress.org/documentation/article/faq-troubleshooting/)

**Comment by thiagommeneses** [comment]
A Pagar.me liberou na tarde de hoje (21/11) uma atualização que corrige o problema. Atualize para a versão **3.4.3** (21/11/2024)
Você pode conferir essas atualizações aqui: [Github](https://github.com/pagarme/woocommerce/releases/tag/3.4.3)

**Correções:**
Problema na tela de Produtos;
Problema com versões antigas e Checkout Blocks;
Aceitar S/N (Não numeral) no campo de Número do endereço;
Problema com transação deslogado e assinatura.

**Comment by thiagommeneses** [comment]
A Pagar.me liberou na tarde de hoje (21/11) uma atualização que corrige o problema. **Atualize para a versão 3.4.3** (21/11/2024)
Você pode conferir essas atualizações aqui: [Github](https://github.com/pagarme/woocommerce/releases/tag/3.4.3)

**Correções**:
Problema na tela de Produtos;
Problema com versões antigas e Checkout Blocks;
Aceitar S/N (Não numeral) no campo de Número do endereço;
Problema com transação deslogado e assinatura.
